apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql
  name: mysql
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: moqaddas
    - name: MYSQL_DATABASE
      value: moqaddas
    - name: MYSQL_USER
      value: moqaddas
    - name: MYSQL_PASSWORD
      value: moqaddas
    image: mysql
    name: mysql
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
