apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mywordpress
  name: mywordpress
spec:
  containers:
  - image: wordpress
    name: mywordpress
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
