- name: "Installing the Docker "
  package:
    name: "docker"
    state: present
- name: "Configure the some repo of docker"
  template:
    src: "daemon.json.j2"
    dest: "/etc/docker/daemon.json"
- name: "Starting the docker service"
  service:
    name: "docker"
    state: started
- name: "Configuring the repo for download the kubeadm"
  template:
    src: "kubeadm.repo.j2"
    dest: "/etc/yum.repos.d/kubeadm.repo"
- name: "Checking kubeadm install or not?"
  command: "rpm -q kubeadm"
  register: check1
  ignore_errors: yes
- name: "Downloading the kubeadm package"
  shell: "yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes"
  when: check1.rc!=0
- name: "Start the service of kubelet"
  service:
    name: "kubelet"
    state: started
- name: "copy joining command"
  copy:
          src: worker_join_command
          dest: wjc.sh
          mode: +x

- name: "Joining to the master node"
  shell: "./wjc.sh"
